name: CI

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'Package*'
      - 'Sources/**'
      - 'Tests/**'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'Package*'
      - 'Sources/**'
      - 'Tests/**'

jobs:
  mac:
    strategy:
      matrix:
        xcode_version: ['11.4', '11.5', '12']
    runs-on: macOS-latest
    timeout-minutes: 10
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
      CX_COMBINE_IMPLEMENTATION: CombineX
      CX_CONTINUOUS_INTEGRATION: "YES"
    steps:
      - uses: actions/checkout@v1
      - name: Swift Version
        run: |
          swift -version
          swift package --version
      - name: Build and Test
        run: swift test

  linux:
    strategy:
      matrix:
        swift_version: ['5.2', '5.3']
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: swift:${{ matrix.swift_version }}
    steps:
      - uses: actions/checkout@v1
      - name: Swift Version
        run: |
          swift -version
          swift package --version
      - name: Build and Test
        run: swift test

  combine:
    runs-on: macOS-latest
    timeout-minutes: 10
    env:
      CX_COMBINE_IMPLEMENTATION: Combine
      CX_CONTINUOUS_INTEGRATION: "YES"
    steps:
      - uses: actions/checkout@v1
      - name: Swift Version
        run: |
          sw_vers -productVersion
          swift -version
          swift package --version
      - name: Build and Test
        run: swift test
